---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/employees":
    get:
      summary: List employees (with filters and pagination)
      tags:
      - Employees
      parameters:
      - name: location
        in: query
        required: false
        description: Filter by location
        schema:
          type: string
      - name: area
        in: query
        required: false
        description: Filter by department
        schema:
          type: string
      - name: time_at_company
        in: query
        required: false
        description: Filter by time at company
        schema:
          type: string
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      responses:
        '200':
          description: Employees successfully listed
  "/api/employees/{id}":
    get:
      summary: Get employee details
      tags:
      - Employees
      parameters:
      - name: id
        in: path
        required: true
        description: Employee ID
        schema:
          type: integer
      responses:
        '200':
          description: Employee found
        '404':
          description: Employee not found
  "/api/feedback":
    get:
      summary: List feedback (with filters and pagination)
      tags:
      - Feedback
      parameters:
      - name: employee_id
        in: query
        required: false
        description: Filter by employee ID
        schema:
          type: integer
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      responses:
        '200':
          description: Feedback successfully listed
  "/api/feedback/{id}":
    get:
      summary: Get feedback details
      tags:
      - Feedback
      parameters:
      - name: id
        in: path
        required: true
        description: Feedback ID
        schema:
          type: integer
      responses:
        '200':
          description: Feedback found
        '404':
          description: Feedback not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
